import React, { useEffect, useState } from 'react';
import DataTable, { createTheme } from 'react-data-table-component';
import useGetAllUsers from '../../Hooks/useGetAllUsers';

const ManageAccount = () => {
    const [allUsers, refetch] = useGetAllUsers()
    const [search, setSearch] = useState("")
    const [tableData, setTableData] = useState([])
    console.log(allUsers)

    const columns = [
        {
            name: "Name",
            selector: row => row.name,
            sortable: true,
        },
        {
            name: "Email",
            selector: row => row.email,
            sortable: true,
        },
        {
            name: "Phone number",
            selector: row => row.phone,
            sortable: true,
        },
        {
            name: "Age",
            selector: row => row.age,
            sortable: true,
        },
        {
            name: "Gender",
            selector: row => row.gender,
            sortable: true,
        },
        {
            name: "City",
            selector: row => row.city,
            sortable: true,
        },
    ];

    const data = [
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
        { name: "Raj", email: "ragsjhf@gmail.com", phone: "012164031", age: "24", gender: "male", city: 'Mumbai' },
        { name: "Taj", email: "tajsjhf@gmail.com", phone: "012164031", age: "22", gender: "male", city: 'Kolkata' },
        { name: "Khan", email: "khansjhf@gmail.com", phone: "012164031", age: "26", gender: "male", city: 'Surat' },
        { name: "Ruposi", email: "ruposhisjhf@gmail.com", phone: "012164031", age: "21", gender: "female", city: 'gujrat' },
        { name: "Batashi", email: "batasisjhf@gmail.com", phone: "012164031", age: "23", gender: "female", city: 'kashmir' },
    ];

    useEffect(() => {
        const result = data.filter((user) => {
            return user.name.toLowerCase().match(search.toLowerCase())
        })
        setTableData(result)
    }, [search])

    createTheme(
        'solarized',
        {
            text: {
                primary: '#268bd2',
                secondary: '#2aa198',
            },
            background: {
                default: '#002b36',
            },
            context: {
                background: '#cb4b16',
                text: '#FFFFFF',
            },
            divider: {
                default: '#073642',
            },
            button: {
                default: '#2aa198',
                hover: 'rgba(0,0,0,.08)',
                focus: 'rgba(255,255,255,.12)',
                disabled: 'rgba(255, 255, 255, .34)',
            },
            sortFocus: {
                default: '#2aa198',
            },
        },
        'dark',
    );

    return (
        <div className='text-white'>
            <p>management Account</p>
            <div className='w-[98%] overflow-hidden mx-auto mt-4 rounded'>

                <DataTable
                    title="User list"
                    columns={columns}
                    data={tableData}
                    theme="solarized"
                    pagination
                    fixedHeader
                    fixedHeaderScrollHeight='70vh'
                    highlightOnHover
                    subHeader
                    subHeaderComponent={
                        <input
                            type='text'
                            placeholder='search by name'
                            className='w-[30%] form-control text-black border rounded-md'
                            value={search}
                            onChange={(e) => setSearch(e.target.value)}
                        />
                    }
                    subHeaderAlign='left'
                    striped="true"
                    dense="false"
                    responsive="true"
                />
            </div>
        </div>
    )
}

export default ManageAccount;